---
layout: default
title: Home
permalink: /
---

# PreOrder Eats

[For Customers](/customers.md) | [For Restaurants](/restaurants.md)

---
layout: default
title: For Customers
permalink: /customers.md
---

# For Customers

Back to [Home](/)

---
layout: default
title: For Restaurants
permalink: /restaurants.md
---

# For Restaurants

Back to [Home](/)

title: PreOrder Eats
theme: jekyll-theme-minimal

[For Customers]({{ site.baseurl }}/customers.md)
[For Restaurants]({{ site.baseurl }}/restaurants.md)
[Home]({{ site.baseurl }}/)
